version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
  server:
    depends_on:
      - mongodb
    build: .
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DB_NAME=NEWS_DB
      - PORT=3000
    ports:
      - 3000:3000

volumes:
  db:
